BildStudionDV.Web/Controllers/AcountController.cs
using BildstudionDV.BI.Context;
using BildstudionDV.BI.ViewModelLogic;
using BildstudionDV.BI.ViewModels;
using BildStudionDV.Web.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;

namespace BildStudionDV.Web.Controllers
{
    public class AcountController : Controller
    {
        IUserProfileVMLogic userLogic;
        IGruppVMLogic gruppLogic;
        List<UserProfileViewModel> userProfileList;
        public AcountController(IUserProfileVMLogic _userLogic, IGruppVMLogic _gruppLogic)
        {
            gruppLogic = _gruppLogic;
            userLogic = _userLogic;
            userProfileList = userLogic.GetUserViewModels();
        }
        [Authorize]
        public IActionResult Index()
        {
            if (User.Identity.Name == "admin" || User.Identity.Name == "piahag")
            {
                return View(userLogic.GetUserViewModels());
            }
            return RedirectToAction("index", "inventarie");
        }
        [Authorize]
        public IActionResult AddUser()
        {
            if (User.Identity.Name == "admin" || User.Identity.Name == "piahag")
            {
                var gruppNamnList = new List<string>();
                foreach (var gruppNamn in gruppLogic.GetAllGrupper())
                {
                    gruppNamnList.Add(gruppNamn.GruppNamn);
                }
                ViewBag.gruppNamnList = gruppNamnList;
                return View(new UserProfileViewModel());
            }
            return RedirectToAction("index", "inventarie");
        }
        [HttpPost]
        [Authorize]
        public IActionResult AddUser(UserProfileViewModel model, string grupp)
        {
            if (User.Identity.Name == "admin" || User.Identity.Name == "piahag")
            {
                if (model.Password == model.NewPassword)
                {
                    if (model.UserName != "" && model.Password != "")
                    {
                        model.AssociatedGrupp = grupp;
                        userLogic.CreateUserAccount(model);
                        userProfileList = userLogic.GetUserViewModels();
                        return RedirectToAction("index");
                    }
                    else
                    {
                        ViewBag.error = "Lösenorden matchar inte, försök igen";
                        return View(model);
                    }
                }
                var gruppNamnList = new List<string>();
                foreach (var gruppNamn in gruppLogic.GetAllGrupper())
                {
                    gruppNamnList.Add(gruppNamn.GruppNamn);
                }
                ViewBag.error = "Något fel i inmatningen, <br />Användarnamn/lösenord/grupp får ej vara tomt";
                return View(model);
            }
            return RedirectToAction("index", "inventarie");
        }
        [Authorize]
        public IActionResult RemoveUser(string namn)
        {
            if (User.Identity.Name == "admin" || User.Identity.Name == "piahag")
            {
                var user = userProfileList.FirstOrDefault(x => x.UserName == namn);
                userLogic.RemoveAccount(user.UserName);
                return RedirectToAction("index");
            }
            return RedirectToAction("index", "inventarie");
        }
        [Authorize]
        public IActionResult EditUser(string namn)
        {
            if (User.Identity.Name == "admin" || User.Identity.Name == "piahag")
            {
                var gruppNamnList = new List<string>();
                foreach (var gruppNamn in gruppLogic.GetAllGrupper())
                {
                    gruppNamnList.Add(gruppNamn.GruppNamn);
                }
                ViewBag.gruppNamnList = gruppNamnList;
                var user = userProfileList.FirstOrDefault(x => x.UserName == namn);
                HttpContext.Response.Cookies.Append("userSelected", user.UserName);
                return View(user);
            }
            return RedirectToAction("index", "inventarie");
        }
        [Authorize]
        [HttpPost]
        public IActionResult EditUser(UserProfileViewModel model, string grupp)
        {
            if (User.Identity.Name == "admin" || User.Identity.Name == "piahag")
            {
                if (model.UserName != null)
                {
                    var oldUserName = HttpContext.Request.Cookies["userSelected"];
                    var user = userLogic.GetUserViewModels().FirstOrDefault(x => x.UserName == oldUserName);
                    user.UserName = model.UserName;
                    user.AssociatedGrupp = grupp;
                    userLogic.UpdateUser(user);
                    userProfileList = userLogic.GetUserViewModels();
                    return RedirectToAction("index");
                }
                var gruppNamnList = new List<string>();
                foreach (var gruppNamn in gruppLogic.GetAllGrupper())
                {
                    gruppNamnList.Add(gruppNamn.GruppNamn);
                }
                ViewBag.gruppNamnList = gruppNamnList;
                ViewBag.error = "Något gick fel, användarnamn kan inte vara tomt, likaså med grupptillhörande.";
                return View(model);
            }
            return RedirectToAction("index", "inventarie");
        }
    }
}

BildStudionDV.Web/Controllers/NärvaroController.cs
using BildstudionDV.BI.MainLogic;
using BildstudionDV.BI.Models;
using BildstudionDV.BI.ViewModelLogic;
using BildstudionDV.BI.ViewModels;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BildStudionDV.Web.Controllers
{
    public class NärvaroController : Controller
    {
        INärvaroVMLogic närvaroLogic;
        IDeltagareVMLogic deltagarLogic;
        IDeltagarViewLogic deltagarViewLogic;
        IMatlistaLogic matlistaLogic;
        List<DeltagareViewModel> deltagarList;
        public NärvaroController(INärvaroVMLogic _närvaroLogic, IDeltagareVMLogic _deltagarLogic, IDeltagarViewLogic _deltagarViewLogic, IMatlistaLogic _matlistaLogic)
        {
            närvaroLogic = _närvaroLogic;
            deltagarLogic = _deltagarLogic;
            deltagarViewLogic = _deltagarViewLogic;
            matlistaLogic = _matlistaLogic;
            deltagarList = deltagarLogic.GetAllDeltagare();
        }
        [Authorize]
        public IActionResult RemoveDeltagare(int id)
        {
            if (User.Identity.Name != "admin" && User.Identity.Name != "piahag")
                return RedirectToAction("index", "inventarie");
            try
            {
                var deltagaren = deltagarList.First(x => x.IdAcesss == id);
                deltagarLogic.RemoveDeltagare(deltagaren.Id);
                deltagarList = deltagarLogic.GetAllDeltagare();
            }
            catch
            {
            }
            return RedirectToAction("Index");
        }
        [Authorize]
        public IActionResult Index()
        {
            if (User.Identity.Name != "admin" && User.Identity.Name != "piahag")
                return RedirectToAction("index", "inventarie");
            ViewBag.date = DateTime.Now.ToString("yyyy-MM-dd");
            var model = deltagarViewLogic.GetAllDeltagareViewData();
            for (int i = 0; i < model.Count; i++)
            {
                if (i == model.Count - 1)
                {
                    ViewBag.DeltagarNames += "'" + model[i].Deltagarn.DeltagarNamn + "'";
                    ViewBag.DeltagarValue += model[i].PercentageAttendence.ToString();
                    ViewBag.Color += "'rgba(255, 99, 132, 0.2)'";
                }
                else
                {
                    ViewBag.DeltagarNames += "'" + model[i].Deltagarn.DeltagarNamn + "',";
                    ViewBag.DeltagarValue += model[i].PercentageAttendence.ToString() + ",";
                    ViewBag.Color += "'rgba(255, 99, 132, 0.2)',";
                }
            }
            return View(model);
        }
        [Authorize]
        public IActionResult AddDeltagare(string message)
        {
            if (User.Identity.Name != "admin" && User.Identity.Name != "piahag")
                return RedirectToAction("index", "inventarie");
            ViewBag.Message = message;
            ViewBag.Workday = Enum.GetValues(typeof(WorkDay)).Cast<WorkDay>().ToList();
            return View(new DeltagareViewModel { IsActive = true });
        }
        [HttpPost]
        [Authorize]
        public IActionResult AddDeltagare(DeltagareViewModel viewModel)
        {
            if (User.Identity.Name != "admin" && User.Identity.Name != "piahag")
                return RedirectToAction("index", "inventarie");
            if (viewModel.DeltagarNamn == null)
                return Redirect("../Närvaro/AddDeltagare?message=InkorrektInmatning");
            deltagarLogic.AddDeltagare(viewModel);
            deltagarList = deltagarLogic.GetAllDeltagare();
            return RedirectToAction("index");

        }
        [Authorize]
        public IActionResult EditDeltagare(int id, string message)
        {
            if (User.Identity.Name != "admin" && User.Identity.Name != "piahag")
                return RedirectToAction("index", "inventarie");
            try
            {
                var model = deltagarList.First(x => x.IdAcesss == id);
                ViewBag.Workday = Enum.GetValues(typeof(WorkDay)).Cast<WorkDay>().ToList();
                ViewBag.Message = message;
                return View(model);
            }
            catch
            {
                return RedirectToAction("index");
            }
        }
        [HttpPost]
        [Authorize]
        public IActionResult EditDeltagare(DeltagareViewModel viewModel)
        {
            if (User.Identity.Name != "admin" && User.Identity.Name != "piahag")
                return RedirectToAction("index", "inventarie");
            var ogDeltagare = deltagarList.First(x => x.IdAcesss == viewModel.IdAcesss);
            viewModel.Id = ogDeltagare.Id;
            if (viewModel.DeltagarNamn == null)
                return Redirect("../Närvaro/EditDeltagare?id="+viewModel.IdAcesss.ToString()+"&message=InkorrektInmatning");
            deltagarLogic.UpdateDeltagare(viewModel);
            deltagarList = deltagarLogic.GetAllDeltagare();
            return RedirectToAction("index");
        }
        [HttpGet]
        [Authorize]
        public IActionResult Attendence(string date)
        {
            if (User.Identity.Name != "admin" && User.Identity.Name != "piahag")
                return RedirectToAction("index", "inventarie");
            
            var compareDate = DateTime.Now.AddYears(-100);
            var dateSupplied = Convert.ToDateTime(date);
            List<AttendenceViewModel> model = new List<AttendenceViewModel>();
            if(dateSupplied > compareDate)
            {
                dateSupplied = GetDateAsLastMonday(dateSupplied);
                ViewBag.date = dateSupplied.ToString("yyyy-MM-dd");
                model = närvaroLogic.GetAttendenceForDate(dateSupplied);
                HttpContext.Response.Cookies.Append("userSelectedDate", dateSupplied.ToString("yyyy-MM-dd"));
                ViewBag.Month = dateSupplied.Month;
                ViewBag.Year = dateSupplied.Year;
            }
            else
            {
                string rawdate = HttpContext.Request.Cookies["userSelectedDate"];
                var dateFromCookie = Convert.ToDateTime(rawdate);
                dateFromCookie = GetDateAsLastMonday(dateFromCookie);
                model = närvaroLogic.GetAttendenceForDate(dateFromCookie);
                ViewBag.date = dateFromCookie.ToString("yyyy-MM-dd");
                ViewBag.Month = dateFromCookie.Month;
                ViewBag.Year = dateFromCookie.Year;
            }
    
            return View(model);
        }

        private DateTime GetDateAsLastMonday(DateTime dateSupplied)
        {
            if (dateSupplied.DayOfWeek == DayOfWeek.Tuesday)
                return dateSupplied.AddDays(- 1);
            if (dateSupplied.DayOfWeek == DayOfWeek.Wednesday)
                return dateSupplied.AddDays(-2);
            if (dateSupplied.DayOfWeek == DayOfWeek.Thursday)
                return dateSupplied.AddDays(-3);
            if (dateSupplied.DayOfWeek == DayOfWeek.Friday)
                return dateSupplied.AddDays(-4);
            if (dateSupplied.DayOfWeek == DayOfWeek.Saturday)
                return dateSupplied.AddDays(-5);
            if (dateSupplied.DayOfWeek == DayOfWeek.Sunday)
                return dateSupplied.AddDays(-6);
            else
                return dateSupplied;
        }

        [HttpPost]
        [Authorize]
        public IActionResult UpdateNärvaro(AttendenceViewModel viewModel)
        {
            if (User.Identity.Name != "admin" && User.Identity.Name != "piahag")
                return RedirectToAction("index", "inventarie");
            string rawdate = HttpContext.Request.Cookies["userSelectedDate"];
            DateTime date = Convert.ToDateTime(rawdate);
            var deltagare = deltagarList.FirstOrDefault(x => x.DeltagarNamn == viewModel.DeltagarNamn);
            var ogViewModel = närvaroLogic.GetAttendenceForDate(date).First(x => x.DeltagarNamn == viewModel.DeltagarNamn);

            ogViewModel.Måndag = viewModel.Måndag;
            ogViewModel.Tisdag = viewModel.Tisdag;
            ogViewModel.Onsdag = viewModel.Onsdag;
            ogViewModel.Torsdag = viewModel.Torsdag;
            ogViewModel.Fredag = viewModel.Fredag;

            närvaroLogic.UpdateAttendence(ogViewModel);
            return RedirectToAction("Attendence");
        }
        [Authorize]
        public IActionResult Diagram(int accessid, int month)
        {
            if (User.Identity.Name != "admin" && User.Identity.Name != "piahag")
                return RedirectToAction("index", "inventarie");
            if(month == 0)
            {
                month = 12;
            }
            ViewBag.SelectValue = month;
            ViewBag.accessid = accessid;
            var deltagare = deltagarList.FirstOrDefault(x => x.IdAcesss == accessid);
            ViewBag.DeltagarNamn = deltagare.DeltagarNamn;
            var model = deltagarViewLogic.GetMonthAttendenceForDeltagare(deltagare.Id, month);
            return View(model);
        }
        [Authorize]
        public IActionResult ExportNärvaro(int accessid, int month)
        {
            if (User.Identity.Name != "admin" && User.Identity.Name != "piahag")
                return RedirectToAction("index", "inventarie");
            if (month == 0)
                month = 12;
            var deltagare = deltagarList.FirstOrDefault(x => x.IdAcesss == accessid);
            var model = deltagarViewLogic.GetMonthAttendenceForDeltagare(deltagare.Id, month);
            bool alternatingrow = true;
            using (var workbook = new XLWorkbook())
            {
        

                var ws = workbook.Worksheets.Add("Månader");
                var col1 = ws.Column("A");
                col1.Width = 10;
                var col2 = ws.Column("B");
                col2.Width = 9;
                var col3 = ws.Column("C");

BildStudionDV.Web/Controllers/WikiController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BildStudionDV.Web.Controllers
{
    public class WikiController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        public IActionResult Konton()
        {
            return View();
        }
        [Authorize]
        public IActionResult Inventarier()
        {
            return View();
        }
        [Authorize]
        public IActionResult KundJobb()
        {
            return View();
        }
        [Authorize]
        public IActionResult Närvaro()
        {
            return View();
        }
    }
}

BildStudionDV.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>    
<html lang="en">    
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - DV Portal</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="~/img/icon_256.ico">
</head>    
<body style="background-image: url(@Url.Content("~/img/cloudwp.png")); background-size: cover; background-repeat:no-repeat;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light text-white bg-dark border-bottom box-shadow mb-3" style="color:aliceblue!important;">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">
                    @if (User.Identity.IsAuthenticated)
                    {

                        <b>
                         DV Portal
                        </b>
                    }
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.Name == "admin" || User.Identity.Name == "piahag")
                        {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-house-door-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M6.5 10.995V14.5a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .146-.354l6-6a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 .146.354v7a.5.5 0 0 1-.5.5h-4a.5.5 0 0 1-.5-.5V11c0-.25-.25-.5-.5-.5H7c-.25 0-.5.25-.5.495z" />
                                    <path fill-rule="evenodd" d="M13 2.5V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z" />
                                </svg>Start
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Wiki" asp-action="index">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-book" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M1 2.828v9.923c.918-.35 2.107-.692 3.287-.81 1.094-.111 2.278-.039 3.213.492V2.687c-.654-.689-1.782-.886-3.112-.752-1.234.124-2.503.523-3.388.893zm7.5-.141v9.746c.935-.53 2.12-.603 3.213-.493 1.18.12 2.37.461 3.287.811V2.828c-.885-.37-2.154-.769-3.388-.893-1.33-.134-2.458.063-3.112.752zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z" />
                                </svg>
                                Wiki
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Acount" asp-action="Index">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-window" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M14 2H2a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1zM2 1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2H2z" />
                                    <path fill-rule="evenodd" d="M15 6H1V5h14v1z" />
                                    <path d="M3 3.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm1.5 0a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm1.5 0a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z" />
                                </svg>Konton
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Inventarie" asp-action="Index">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-archive-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z" />
                                </svg>
                                Inventarier
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Jobb" asp-action="Index">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bag-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M8 1a2.5 2.5 0 0 0-2.5 2.5V4h5v-.5A2.5 2.5 0 0 0 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5z" />
                                </svg>KundJobb
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Närvaro" asp-action="Index">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bar-chart-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <rect width="4" height="5" x="1" y="10" rx="1" />
                                    <rect width="4" height="9" x="6" y="6" rx="1" />
                                    <rect width="4" height="14" x="11" y="1" rx="1" />
                                </svg>
                                Närvaro
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Logout">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-x-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm6.146-2.854a.5.5 0 0 1 .708 0L14 6.293l1.146-1.147a.5.5 0 0 1 .708.708L14.707 7l1.147 1.146a.5.5 0 0 1-.708.708L14 7.707l-1.146 1.147a.5.5 0 0 1-.708-.708L13.293 7l-1.147-1.146a.5.5 0 0 1 0-.708z" />
                                </svg>Logga ut
                            </a>
                        </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                        @if (User.Identity.Name == "admin" || User.Identity.Name == "piahag")
                            {
                            }
                            else
                            {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Inventarie" asp-action="Index">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-archive-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z" />
                                </svg>
                                Inventarier
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Logout">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-x-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm6.146-2.854a.5.5 0 0 1 .708 0L14 6.293l1.146-1.147a.5.5 0 0 1 .708.708L14.707 7l1.147 1.146a.5.5 0 0 1-.708.708L14 7.707l-1.146 1.147a.5.5 0 0 1-.708-.708L13.293 7l-1.147-1.146a.5.5 0 0 1 0-.708z" />
                                </svg>Logga ut
                            </a>
                        </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container rounded" style="background-color: black; color:white; min-height: 80vh;">
        <main role="main" class="pb-3">
            <br />
            <div class="container rounded" style="background-color:aliceblue; color:black;min-height:75vh;">
                @RenderBody()
                </div>
        </main>
    </div>
    <br />

    <footer class="border-top footer bgdark text-muted" style="background-color: black; color:white;">
        <div class="container" style="background-color: black; color:white;">
            © 2020 @if (User.Identity.IsAuthenticated)
            {
                <b>BildstudionDV</b>
            }
        </div>
    </footer>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/js/chartjs-datalabels.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>    
</html>   